#include "Effects/EffectBasePS.h"
#include "Effects/EmptyEffectPS.h"
#include "Effects/FixedLengthRainbowCycle/FixedLengthRainbowCyclePS.h"
#include "Effects/CrossFadeCycle/CrossFadeCyclePS.h"
#include "Effects/CrossFadeCycleRand/CrossFadeCycleRandPS.h"
#include "Effects/RandomColors/RandomColorsPS.h"